#Generated by soba https://github.com/justinwoo/soba
{ pkgs ? import <nixpkgs> {} }:

{
    "aff" = pkgs.stdenv.mkDerivation {
      name = "aff";
      version = "v5.1.2";
      fetched = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-aff.git";
        rev = "78916a9c7e6d203f1d9f441c8eaa257d6475e978";
        sha256 = "1ygjxbm2bqw82sm17szhzz4jihvbg9mszx1ii0n3sj72bnz02avz";
      };
    };

    "arrays" = pkgs.stdenv.mkDerivation {
      name = "arrays";
      version = "v5.3.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-arrays.git";
        rev = "463dcacb99455de5e28ac4a3312bb795f293d2d9";
        sha256 = "1z8i4mr30mjsvmw743g0m1yxfgqa9rhbgq7jq3955mg7j80j5r7w";
      };
    };

    "avar" = pkgs.stdenv.mkDerivation {
      name = "avar";
      version = "v3.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-avar.git";
        rev = "17914413130490318a475e9de6a9244aaaa097d2";
        sha256 = "14g05jm2xricy5b9vn4k4lhc9lzi5jvpvv85h10s17kn4wwi9igk";
      };
    };

    "bifunctors" = pkgs.stdenv.mkDerivation {
      name = "bifunctors";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-bifunctors.git";
        rev = "1062425892b4a1c734ec653dded22546e3063b27";
        sha256 = "1bdra5fbkraglqrrm484vw8h0wwk48kzkn586v4y7fg106q1q386";
      };
    };

    "catenable-lists" = pkgs.stdenv.mkDerivation {
      name = "catenable-lists";
      version = "v5.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-catenable-lists.git";
        rev = "d81b7df30d9879d0bb531b3102fb36f429c2f12e";
        sha256 = "0mbpb8xr9a7a4bvawhki7js5cbv7c0lv0vdwb6r8nmv6b61gzg27";
      };
    };

    "console" = pkgs.stdenv.mkDerivation {
      name = "console";
      version = "v4.3.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-console.git";
        rev = "8224f6e9af1dba922139038edc49e55f20c1fbd4";
        sha256 = "0saaacddyhb4rdjy6v0hfwydwzcgy0ph5syxs4zb6c7wiyb4p9ll";
      };
    };

    "const" = pkgs.stdenv.mkDerivation {
      name = "const";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-const.git";
        rev = "bc5db27b0ed3947fa5e2074ccbab01236eec3fa4";
        sha256 = "0qbd2aisax52yw6sybdhs7na943cbsd6mylhhgsamrf7hzh6v51p";
      };
    };

    "contravariant" = pkgs.stdenv.mkDerivation {
      name = "contravariant";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-contravariant.git";
        rev = "cb69db0253c2e2ed3fef784dad58f3418a8ee834";
        sha256 = "0dd17lwlybpz4i54cxnqdgy38rjlbw9p7bw1r43is6z3kdc8983a";
      };
    };

    "control" = pkgs.stdenv.mkDerivation {
      name = "control";
      version = "v4.2.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-control.git";
        rev = "05d40c5855a0eda3bc396a3d815eaf213a0534e6";
        sha256 = "1nm45khn2dvlyv059nzpz1w7d3nfsvq45hnb2qllrbzyv7rlxmi8";
      };
    };

    "datetime" = pkgs.stdenv.mkDerivation {
      name = "datetime";
      version = "v4.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-datetime.git";
        rev = "9e76abe96f45a68eb0bb23d0afd56031a8070bee";
        sha256 = "06ghfvbvd5sd0q014qi8j8glk2g2j9f8z8cwq2318kllp92gz07q";
      };
    };

    "decimals" = pkgs.stdenv.mkDerivation {
      name = "decimals";
      version = "v5.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/sharkdp/purescript-decimals.git";
        rev = "4911f744fb7db6519758b6993edc28d0f81e0a89";
        sha256 = "1ad56xf8i7mwqlp718ik12dvc8aqwjxfpk7d8hdyjwzhf7b1ws2n";
      };
    };

    "distributive" = pkgs.stdenv.mkDerivation {
      name = "distributive";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-distributive.git";
        rev = "3a43c0690883816e9ebeac510698423cfff5c174";
        sha256 = "0zbn0yq1vv7fbbf1lncg80irz0vg7wnw9b9wrzxhdzpbkw4jinsl";
      };
    };

    "effect" = pkgs.stdenv.mkDerivation {
      name = "effect";
      version = "v2.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-effect.git";
        rev = "6caa8e1e162a21eed025613c2c19194b996ef779";
        sha256 = "1vqw5wrdxzh1ww6z7271xr4kg4mx0r3k3mwg18dmgmzj11wbn2wh";
      };
    };

    "either" = pkgs.stdenv.mkDerivation {
      name = "either";
      version = "v4.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-either.git";
        rev = "8b4b38a729f8e88750b03e5c7baf2b3863ce4742";
        sha256 = "12j7vvjly0bgxidxmb2pflx0zy7x425dnvxk2y1pm66n0hbsq7ns";
      };
    };

    "enums" = pkgs.stdenv.mkDerivation {
      name = "enums";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-enums.git";
        rev = "19800105b556798ea5650f8a01bfe5ea17cfc6eb";
        sha256 = "0qq0pgmq497nfml0y8xb2qdpga5xqp9sqq4ilv1rpyhg1v7nzb6v";
      };
    };

    "exceptions" = pkgs.stdenv.mkDerivation {
      name = "exceptions";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exceptions.git";
        rev = "9012eb08749e9ccd5da45bdece5d576e5fc0b0db";
        sha256 = "17s0rg9k4phivhx9j3l2vqqfdhk61gpj1xfqy8w6zj3rnxj0b2cv";
      };
    };

    "exists" = pkgs.stdenv.mkDerivation {
      name = "exists";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exists.git";
        rev = "ef53359aebc09bf863800ca86ad1dcd76f0b08ae";
        sha256 = "0bbdbw3jaqyi8dj2d52zvfgx4vl84d8cr6hp43vy8lfjfcbj0wlk";
      };
    };

    "foldable-traversable" = pkgs.stdenv.mkDerivation {
      name = "foldable-traversable";
      version = "v4.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foldable-traversable.git";
        rev = "29d5b873cc86f17e0082d777629819a96bdbc7a1";
        sha256 = "03x89xcmphckzjlp4chc7swrpw347ll5bvr2yp7x9v2jqw2jlyi1";
      };
    };

    "free" = pkgs.stdenv.mkDerivation {
      name = "free";
      version = "v5.2.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-free.git";
        rev = "f686f5fc07766f3ca9abc83b47b6ad3da326759a";
        sha256 = "1bwj0ay7q9lm4ir29jy549m05jvaqik1s615biv23y51ngx3fn49";
      };
    };

    "functions" = pkgs.stdenv.mkDerivation {
      name = "functions";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functions.git";
        rev = "c63451ae74f6fba7a4eede5f87208a73c537af77";
        sha256 = "0675k5kxxwdvsjs6a3is8pwm3hmv0vbcza1b8ls10gymmfz3k3hj";
      };
    };

    "functors" = pkgs.stdenv.mkDerivation {
      name = "functors";
      version = "v3.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functors.git";
        rev = "96bcf8a970a40115a76a20d19e50aa3b524adcf3";
        sha256 = "1cnn3zhk6qcyiwbbpvrdqgsbch4qihx2y9d6sv45bvd8kzrbd306";
      };
    };

    "gen" = pkgs.stdenv.mkDerivation {
      name = "gen";
      version = "v2.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-gen.git";
        rev = "36f36f03f082b57e402c27f1513f8935caa54101";
        sha256 = "0pk68cn1s89hql30ydks9gh34gbxg391smi2albx3qvxnfkrpxca";
      };
    };

    "generics-rep" = pkgs.stdenv.mkDerivation {
      name = "generics-rep";
      version = "v6.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-generics-rep.git";
        rev = "aae27ba1de21dda342dcdfc8b3cc5b951bd5b3ec";
        sha256 = "15vchzbcvf6byks90q14lvcwb8hnxqzm2mrlxi7v1f7has4s74kn";
      };
    };

    "globals" = pkgs.stdenv.mkDerivation {
      name = "globals";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-globals.git";
        rev = "8e6d69c36b6fd8c988a3664fc033ad11dbdd5860";
        sha256 = "03h4npdbsjr1mkjasdi071l0cl7zdf3l76a8f0x4ghx47yvpgadn";
      };
    };

    "identity" = pkgs.stdenv.mkDerivation {
      name = "identity";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-identity.git";
        rev = "1b7938abdc8cb28c0ac5f80f63405d53e3173a8e";
        sha256 = "1scdgbfkphfmapw7p9rnsiynpmqzyvnal2glzj450q51f8g1dhld";
      };
    };

    "integers" = pkgs.stdenv.mkDerivation {
      name = "integers";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-integers.git";
        rev = "3850da9cd96b37c71685b6bc3bf0cb489baefc93";
        sha256 = "17d4bfpnrmbxlc7hhhrvnli70ydaqyr26zgvc9q52a76zgdcb4cf";
      };
    };

    "invariant" = pkgs.stdenv.mkDerivation {
      name = "invariant";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-invariant.git";
        rev = "b704c5bda262719ca5cc88a3f8554edff8f03256";
        sha256 = "1fimpbh3yb7clvqxcdf4yf9im64z0v2s9pbspfacgq5b4vshjas9";
      };
    };

    "js-timers" = pkgs.stdenv.mkDerivation {
      name = "js-timers";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-js-timers.git";
        rev = "8206d3d8034357b4665828e52f7ff1b8cb46611e";
        sha256 = "1a8092sli7zqw1wflibhjza1ww21dxl7x7r602iazzwh2g70v4dg";
      };
    };

    "lazy" = pkgs.stdenv.mkDerivation {
      name = "lazy";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lazy.git";
        rev = "5bbd04f507a704f39aa756b5e12ed6665205fe2e";
        sha256 = "156q89l4nvvn14imbhp6xvvm82q7kqh1pyndmldmnkhiqyr84vqv";
      };
    };

    "lcg" = pkgs.stdenv.mkDerivation {
      name = "lcg";
      version = "v2.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lcg.git";
        rev = "596bcb17bd550397735220f919df52bcd0038fe0";
        sha256 = "1851cq2g84jzjbvbmncbivbhaqzj9zv5ni3gs14k04nmx2brxmvj";
      };
    };

    "lists" = pkgs.stdenv.mkDerivation {
      name = "lists";
      version = "v5.4.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lists.git";
        rev = "62900a56f6864638c952575dfd211a1cc55be7da";
        sha256 = "0l0jiqhcjzkg4nv2a6h2vdf4izr9mf7cxc86cq1hf3j4dh6spym1";
      };
    };

    "math" = pkgs.stdenv.mkDerivation {
      name = "math";
      version = "v2.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-math.git";
        rev = "8be36d24f9d2d8795adf04791446bbc458297b9b";
        sha256 = "1msmy9w7y6fij62sdc55w68gpwkhm6lhgc8qjisjk4sxx1wdg1rr";
      };
    };

    "maybe" = pkgs.stdenv.mkDerivation {
      name = "maybe";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-maybe.git";
        rev = "81f0397636bcbca28642f62421aebfd9e1afa7fb";
        sha256 = "073wa0d51daxdwacfcxg5pf6ch63n4ii55xm1ih87bxrg8mp52mx";
      };
    };

    "newtype" = pkgs.stdenv.mkDerivation {
      name = "newtype";
      version = "v3.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-newtype.git";
        rev = "7d85fa6a040208c010b05f7c23af6a943ba08763";
        sha256 = "0qvk9p41miy806b05b4ikbr3if0fcyc35gfrwd2mflcxxp46011c";
      };
    };

    "nonempty" = pkgs.stdenv.mkDerivation {
      name = "nonempty";
      version = "v5.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-nonempty.git";
        rev = "36ca3b2fa6d98b1c9d2ee05643341e496fbeab57";
        sha256 = "1vz174sg32cqrp52nwb2vz9frrzmdwzzlgl4vc2cm5wlf2anirxj";
      };
    };

    "numbers" = pkgs.stdenv.mkDerivation {
      name = "numbers";
      version = "v7.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/sharkdp/purescript-numbers.git";
        rev = "6262a5f17dcdfba11dfae03f4fa8eec02f7ed29f";
        sha256 = "1l9s22fkjf7wc0zd3wjax4hlif7gqh6ij0ijb8sq20mfh2xl4hj8";
      };
    };

    "ordered-collections" = pkgs.stdenv.mkDerivation {
      name = "ordered-collections";
      version = "v1.6.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-ordered-collections.git";
        rev = "54af8b281bf01acfc14e147debec76974901e93c";
        sha256 = "0r48p94d3cyzni2z7ikzcap472k23dx8zq37c1prmjb01v03mfvc";
      };
    };

    "orders" = pkgs.stdenv.mkDerivation {
      name = "orders";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-orders.git";
        rev = "80e22c22c72c846e09ef9dfcdb40b3eee39118d6";
        sha256 = "13p1sm4dxkmxhld9x5qqg62iiajjb3qpzs66c1r24y5fs4zsfry4";
      };
    };

    "pairs" = pkgs.stdenv.mkDerivation {
      name = "pairs";
      version = "v7.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/sharkdp/purescript-pairs.git";
        rev = "8c220e4f51c33ef04291cab60af69729f768f8ea";
        sha256 = "1zd3fvxw3kpyb066rhmadh97ppfmypsl2q1w23xqaywwzpx2n3a3";
      };
    };

    "parallel" = pkgs.stdenv.mkDerivation {
      name = "parallel";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-parallel.git";
        rev = "4d6c8b05041a36c300dfca2ba8f1f3443ca26bc6";
        sha256 = "1d5bnagabw2k8yxywkygwrpblb2ggqh2fhpqfrx2sj1y53x332hg";
      };
    };

    "parsing" = pkgs.stdenv.mkDerivation {
      name = "parsing";
      version = "v5.0.3";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-parsing.git";
        rev = "e801a0ef42f3211b1602a94a269eef7ce551423f";
        sha256 = "0m5xvb5kis28laj3navyyakyq408vw115c2dvngf1vljzh1hk5kj";
      };
    };

    "partial" = pkgs.stdenv.mkDerivation {
      name = "partial";
      version = "v2.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-partial.git";
        rev = "76b63a324f7eafbb859256771b5bb7404082af96";
        sha256 = "11qr80989g7xmvw1brnrclsbg2wdkbr5k3cqpngfip3nnirrypcn";
      };
    };

    "prelude" = pkgs.stdenv.mkDerivation {
      name = "prelude";
      version = "v4.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-prelude.git";
        rev = "a96663b34364fdd0885a200955e35b99f4e58c43";
        sha256 = "1frvjrv0mr508r6683l1mp5rzm1y2dz76fz40zf4k2c64sy6y1xm";
      };
    };

    "psci-support" = pkgs.stdenv.mkDerivation {
      name = "psci-support";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-psci-support.git";
        rev = "a66a0fa8661eb8b5fe75cc862f4e2df2835c058d";
        sha256 = "0jd773zcklr6hjddqingzmk20a0afpm2r9pczfjbj0d93pbxb4xh";
      };
    };

    "quantities" = pkgs.stdenv.mkDerivation {
      name = "quantities";
      version = "v10.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/sharkdp/purescript-quantities.git";
        rev = "92feca4ec665d129d40aa31dbd70da34414cb483";
        sha256 = "0dw2rmvzapfwpjlyvvggghkn9yv261zx8r9ayyfrfbqympyl044m";
      };
    };

    "quickcheck" = pkgs.stdenv.mkDerivation {
      name = "quickcheck";
      version = "v6.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-quickcheck.git";
        rev = "6289a80570acd5aec3ea89dc673cf10cdaf5794a";
        sha256 = "0b6208067krf81kzq2hbxs68386hcicbscwxbj5nck07ivjjvqh0";
      };
    };

    "random" = pkgs.stdenv.mkDerivation {
      name = "random";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-random.git";
        rev = "75e6b21edbe0eec78c28ff3bd8265998f2ea0b45";
        sha256 = "0k37v7z529adx6ypxj0xjyfrz45qia6p0vki2wpvi8lik7c698gf";
      };
    };

    "record" = pkgs.stdenv.mkDerivation {
      name = "record";
      version = "v2.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-record.git";
        rev = "42a15ba34d860f4d8f899836956bf09659a0256b";
        sha256 = "1l7ixb0gc2man36181g3hdf46sjp7xh0kv8bgrvalxfisjmd12v0";
      };
    };

    "refs" = pkgs.stdenv.mkDerivation {
      name = "refs";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-refs.git";
        rev = "e8b175477661e433175e76548168290c40e0ce4b";
        sha256 = "08161iy1xbafzblv033v84156azpcqkiw9v9d6gliphrq5fm17gm";
      };
    };

    "st" = pkgs.stdenv.mkDerivation {
      name = "st";
      version = "v4.0.2";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-st.git";
        rev = "3fcc99181225c1a7693d63024d912ead1a62c495";
        sha256 = "04qbin35xkir2zbv3prnxz2h0p7nbw4j38a04s6km2qgd5d2gzzh";
      };
    };

    "strings" = pkgs.stdenv.mkDerivation {
      name = "strings";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-strings.git";
        rev = "94c843b93142d0edf1c31ec075c40b6984c3dc7b";
        sha256 = "147l3l3fzn7liparhm2y3p8j4ck1lblra5j493p2hy5yy5ndznc8";
      };
    };

    "tailrec" = pkgs.stdenv.mkDerivation {
      name = "tailrec";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tailrec.git";
        rev = "8946bf9d9f68a8469198b4d512593d4a2a97cada";
        sha256 = "1qgxjim8wmw9m2iy1cq0kx5n6lh3bs52w5mdxc7k4wb880d9h32w";
      };
    };

    "test-unit" = pkgs.stdenv.mkDerivation {
      name = "test-unit";
      version = "v15.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/bodil/purescript-test-unit.git";
        rev = "351c55b632e0c0ebffae05837909995a03de3406";
        sha256 = "06lb90vppa7naqqwz7wbvlkkyz86pbdd3ycw3d2iygvxbzkz8xjn";
      };
    };

    "transformers" = pkgs.stdenv.mkDerivation {
      name = "transformers";
      version = "v4.2.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-transformers.git";
        rev = "0e473e5ef0e294615ca0d9aab0bcffee47b2870d";
        sha256 = "03qmvl9s7lbvm73dy9ps6qp39pdcm91hb8yakgj7aq8hgpj7b6bg";
      };
    };

    "tuples" = pkgs.stdenv.mkDerivation {
      name = "tuples";
      version = "v5.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tuples.git";
        rev = "0036bf9d99b721fd0f2e539d24e18e484b016927";
        sha256 = "045nsy0r2g51gih0wjhcvhl6gfr8947mlrqwg644ygz72rjm8wq4";
      };
    };

    "type-equality" = pkgs.stdenv.mkDerivation {
      name = "type-equality";
      version = "v3.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-type-equality.git";
        rev = "2cdae51c394401cd5fc04b03c341273b41532b7d";
        sha256 = "1b7szyca5s96gaawvgwrw7fa8r7gqsdff7xhz3vvngnylv2scl3w";
      };
    };

    "unfoldable" = pkgs.stdenv.mkDerivation {
      name = "unfoldable";
      version = "v4.0.2";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unfoldable.git";
        rev = "be3262a9dc48e794676b1b2883987331d4be6fd7";
        sha256 = "0lzhx030c5933maxcjwk6kzlvbxky1kiwrymqf1dp5wbrar3jyv4";
      };
    };

    "unicode" = pkgs.stdenv.mkDerivation {
      name = "unicode";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-unicode.git";
        rev = "bb70f5a17aa9bcad05104c5a3f191fd75bb3d2ce";
        sha256 = "1a53jv7pzyjk5v6kmwwy50d3l8d26k0id59sn8g3lzkih24nalhp";
      };
    };

    "unsafe-coerce" = pkgs.stdenv.mkDerivation {
      name = "unsafe-coerce";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unsafe-coerce.git";
        rev = "fa6a5ca9b4581c00ee0b8539306a49badb7bee60";
        sha256 = "0k9255mk2mz6xjb11pwkgfcblmmyvr86ig5kr92jwy95xim09zip";
      };
    };
}
